<?php

/**
 * @file
 * Implements pipwave payment services for use with Drupal Commerce.
 */

/**
 * Implements hook_permission().
 */
function commerce_pipwave_permission() {
    return array(
        'administer commerce pipwave' => array(
            'title' => t('Administer Commerce pipwave'),
            'description' => t('Perform administration tasks for Commerce pipwave gateway.'),
        ),
    );
}

/**
 * Implements hook_menu().
 */
function commerce_pipwave_menu() {
    $items = array(
        'admin/commerce/config/pipwave' => array(
            'title' => 'pipwave Settings',
            'description' => 'pipwave API settings.',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('commerce_pipwave_admin_form'),
            'access arguments' => array('administer commerce pipwave'),
        ),
        'admin/commerce/callback' => array(
            'title' => 'callback',
            'page callback' => 'commerce_pipwave_callback',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK
        )
    );

    return $items;
}

/**
 * Commerce pipwave admin form.
 *
 * @todo Add configuration to select available payment methods and currency.
 */
function commerce_pipwave_admin_form($form, &$form_state) {
    $form['merchant']['pipwave_logo'] = array(
        '#markup' => l(theme_image(array(
            'path' => drupal_get_path('module', 'commerce_pipwave') . '/images/pipwave-logo.png',
            'alt' => t('pipwave - Simple, reliable, and cost-effective way to accept payments online.'),
            'title' => t('pipwave - Simple, reliable, and cost-effective way to accept payments online.'),
            'attributes' => array(),
                )), 'https://www.pipwave.com', array('html' => TRUE, 'attributes' => array('target' => '_blank', 'style' => 'display: block; margin-bottom: 10px;'))
        ),
    );
    $form['merchant']['api_key'] = array(
        '#type' => 'textfield',
        '#title' => t('API Key'),
        '#size' => 64,
        '#maxlength' => 64,
        '#required' => TRUE,
        '#default_value' => variable_get('commerce_pipwave_api_key'),
        '#description' => t("API Key provided by pipwave in <a href='https://merchant.pipwave.com/development-setting/index' target='_blank'>Development > Setting</a>", array('html' => true))
    );
    $form['merchant']['api_secret'] = array(
        '#type' => 'textfield',
        '#title' => t('API Secret'),
        '#size' => 64,
        '#maxlength' => 64,
        '#required' => TRUE,
        '#default_value' => variable_get('commerce_pipwave_api_secret'),
        '#description' => t("API Secret provided by pipwave in <a href='https://merchant.pipwave.com/development-setting/index' target='_blank'>Development > Setting</a>", array('html' => true))
    );
    $form["merchant"]["mode"] = array(
        '#type' => 'checkbox',
        '#title' => 'Enable test mode',
        '#default_value' => variable_get('commerce_pipwave_test_mode'),
    );
    $form["merchant"]["processing_fee_group"] = array(
        '#type' => 'textfield',
        '#title' => t('Payment Processing Fee Group Reference ID'),
        '#size' => 64,
        '#maxlength' => 64,
        '#default_value' => variable_get('commerce_pipwave_surcharge_group'),
        '#description' => t("Payment Processing Fee Group configured in pipwave <a href='https://merchant.pipwave.com/account/set-processing-fee-group#general-processing-fee-group' target='_blank'>Account > General</a>.<br>Processing fee will be applied on all customers once this setting is configured.", array(
            'html' => true
        )),
    );

    $form['submit'] = array('#type' => 'submit', '#value' => t('Save'));

    return $form;
}

function commerce_pipwave_admin_form_submit($form, &$form_state) {
    $values = $form_state['values'];
    // Save settings into variable table.
    variable_set('commerce_pipwave_api_key', $values['api_key']);
    variable_set('commerce_pipwave_api_secret', $values['api_secret']);
    variable_set('commerce_pipwave_test_mode', $values['mode']);
    variable_set('commerce_pipwave_surcharge_group', $values['processing_fee_group']);
    //Display messagge
    drupal_set_message(t('Settings has been done.'));
}

/**
 * Implements hook_commerce_payment_method_info().
 *
 * @todo Allow terminal payment.
 */
function commerce_pipwave_commerce_payment_method_info() {
    $payment_methods = array();
    $payment_methods['commerce_pipwave'] = array(
        'title' => t('pipwave'),
        'description' => t('Pay via pipwave.'),
        'terminal' => FALSE,
        'active' => TRUE,
        'offsite' => TRUE,
    );

    return $payment_methods;
}

/**
 * Payment method callback: submit form.
 */
function commerce_pipwave_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
    // Unset all previous orders from session.
    drupal_session_start();
    unset($_SESSION['commerce_pipwave']);

    $form = array();
    // Fetch list of enabled payment methods from pipwave api
    $form['pipwave_logo'] = array(
        '#markup' => l(
                theme_image(array(
            'path' => drupal_get_path('module', 'commerce_pipwave') . '/images/pipwave-logo.png',
            'alt' => t('pipwave - Simple, reliable, and cost-effective way to accept payments online.'),
            'title' => t('pipwave - Simple, reliable, and cost-effective way to accept payments online.'),
                )), 'https://www.pipwave.com', array('html' => TRUE, 'attributes' => array('target' => '_blank', 'style' => 'display: block; margin: 10px 0;'))
        ),
    );

    $form['pipwave_message'] = array(
        "#markup" => "Press <strong>Continue to next step</strong> to make payment via pipwave."
    );

    return $form;
}

/**
 * Implements hook_redirect_form().
 */
function commerce_pipwave_redirect_form($form, &$form_state, $order, $payment_method) {
    if (variable_get("commerce_pipwave_api_key") == null || variable_get("commerce_pipwave_api_secret") == null) {
        drupal_set_message(t('Missing pipwave API Key or API Secret. Kindly check your pipwave setting.'), 'error');
        return array();
    }
    $settings = array(
        'return' => url('checkout/' . $order->order_id . '/payment/return/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)),
        'cancel_return' => url('checkout/' . $order->order_id . '/payment/back/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)),
        'callback' => url('admin/commerce/callback', array('absolute' => TRUE)),
        'payment_method' => $payment_method['instance_id'],
    );
    return commerce_pipwave_order_form($form, $form_state, $order, $payment_method['settings'] + $settings);
}

function commerce_pipwave_order_form($form, &$form_state, $order, $settings) {
    $wrapper = entity_metadata_wrapper('commerce_order', $order);
    $currency_code = $wrapper->commerce_order_total->currency_code->value();
    $amount = number_format(commerce_currency_amount_to_decimal($order->commerce_order_total[LANGUAGE_NONE][0]['amount'], $order->commerce_order_total[LANGUAGE_NONE][0]['currency_code']), 2);
    global $language;
    $data = array(
        'action' => 'initiate-payment',
        'timestamp' => time(),
        'api_key' => variable_get('commerce_pipwave_api_key'),
        'txn_id' => $order->order_number . "",
        'amount' => $amount,
        'currency_code' => $currency_code,
        'short_description' => 'Payment for Order#' . $order->order_number,
        'session_info' => array(
            'ip_address' => $order->revision_hostname,
            'language' => isset($language->language) ? $language->language : ''
        ),
        'api_override' => array(
            'success_url' => $settings['return'],
            'fail_url' => $settings['cancel_return'],
            'notification_url' => $settings['callback']
        ),
        'buyer_info' => array(
            'id' => $order->uid,
            'email' => $order->mail,
            'surcharge_group' => variable_get('commerce_pipwave_surcharge_group')
        )
    );
    module_load_include('inc', 'addressfield', 'addressfield.administrative_areas');
    module_load_include('inc', 'locale', 'locale');
    $countries = country_get_list();
    if (isset($order->commerce_customer_billing[LANGUAGE_NONE][0])) {
        $billing_address = entity_metadata_wrapper('commerce_order', $order)->commerce_customer_billing->commerce_customer_address->value();
        $administrative_areas = addressfield_get_administrative_areas($billing_address['country']);
        $data['billing_info'] = array(
            'name' => $billing_address['name_line'],
            'address1' => $billing_address['thoroughfare'],
            'address2' => $billing_address['premise'],
            'city' => $billing_address['locality'],
            'state' => isset($administrative_areas[$billing_address['administrative_area']]) ? $administrative_areas[$billing_address['administrative_area']] : '',
            'zip' => $billing_address['postal_code'],
            'country' => isset($countries[$billing_address['country']]) ? $countries[$billing_address['country']] : '',
            'country_iso2' => $billing_address['country']
        );
        $data['buyer_info']['first_name'] = $billing_address['first_name'];
        $data['buyer_info']['last_name'] = $billing_address['last_name'];
        $data['buyer_info']['country_code'] = $billing_address['country'];
    }
    $shipping_address = "";
    if (isset($order->commerce_customer_shipping[LANGUAGE_NONE][0])) {
        $shipping_address = entity_metadata_wrapper('commerce_order', $order)->commerce_customer_shipping->commerce_customer_address->value();
        $administrative_areas = addressfield_get_administrative_areas($shipping_address['country']);
        $data['shipping_info'] = array(
            'name' => $shipping_address['name_line'],
            'address1' => $shipping_address['thoroughfare'],
            'address2' => $shipping_address['premise'],
            'city' => $shipping_address['locality'],
            'state' => isset($administrative_areas[$shipping_address['administrative_area']]) ? $administrative_areas[$shipping_address['administrative_area']] : '',
            'zip' => $shipping_address['postal_code'],
            'country' => isset($countries[$shipping_address['country']]) ? $countries[$shipping_address['country']] : '',
            'country_iso2' => $shipping_address['country']
        );
    }
    //get product details
    foreach ($order->commerce_line_items[LANGUAGE_NONE] as $line) {
        $line_item = commerce_line_item_load($line['line_item_id']);
        if (isset($line_item->commerce_product[LANGUAGE_NONE][0]['product_id'])) {
            $product = commerce_product_load($line_item->commerce_product[LANGUAGE_NONE][0]['product_id']);
            if ($product) {
                $data['item_info'][] = array(
                    "name" => $product->title,
                    "description" => $product->title . ' x ' . $line_item->quantity,
                    "amount" => number_format(commerce_currency_amount_to_decimal($line_item->commerce_unit_price[LANGUAGE_NONE][0]['amount'], $line_item->commerce_unit_price[LANGUAGE_NONE][0]['currency_code']), 2),
                    "currency_code" => $line_item->commerce_unit_price[LANGUAGE_NONE][0]['currency_code'],
                    "quantity" => $line_item->quantity,
                    "sku" => $product->sku
                );
            }
        }
    }
    $signature_param = array(
        'api_key' => variable_get('commerce_pipwave_api_key'),
        'api_secret' => variable_get('commerce_pipwave_api_secret'),
        'txn_id' => $data['txn_id'],
        'amount' => $data['amount'],
        'currency_code' => $data['currency_code'],
        'action' => $data['action'],
        'timestamp' => $data['timestamp']
    );
    $data['signature'] = commerce_pipwave_generate_signature($signature_param);
    $response = commerce_pipwave_send_request($data, variable_get('commerce_pipwave_test_mode'));
    if ($response['status'] == 200) {
        $api_data = json_encode([
            'api_key' => variable_get('commerce_pipwave_api_key'),
            'token' => $response['token'],
        ]);
        $sdk_url = (variable_get('commerce_pipwave_test_mode') == '1') ? '//staging-checkout.pipwave.com/sdk/' : '//checkout.pipwave.com/sdk/';
        $form['payment_method'] = array(
            '#markup' =>
            '<div id="pwscript" class="text-center"></div>
                    <div id="pwloading" style="text-align: center;">
                        <i class="fa fa-spinner fa-spin fa-fw margin-bottom" style="font-size: 3em; color: #7a7a7a;"></i>
                        <span class="sr-only">Loading...</span>
                    </div>
                    <script type="text/javascript">
                        var pwconfig = ' . $api_data . ';
                        (function (_, p, w, s, d, k) {
                            var a = _.createElement("script");
                            a.setAttribute("src", w + d);
                            a.setAttribute("data-main", w + s);
                            a.setAttribute("id", k);
                            setTimeout(function() {
                                var reqPwInit = (typeof reqPipwave != "undefined");
                                if (reqPwInit) {
                                    reqPipwave.require(["pw"], function(pw) {
                                        pw.setOpt(pwconfig);
                                        pw.startLoad();
                                    });
                                } else {
                                    _.getElementById(k).parentNode.replaceChild(a, _.getElementById(k));
                                }
                            }, 800);
                        })(document, "script", "' . $sdk_url . '", "pw.sdk.min.js", "pw.sdk.min.js", "pwscript");
        </script>');
    } else {
        $form['payment_method'] = array(
            '#markup' => isset($response['message']) ? (is_array($response['message']) ? implode('; ', $response['message']) : $response['message']) : "Error occured",
        );
    }
    
    return $form;
}

function commerce_pipwave_redirect_form_validate($response, $order, $payment_method) {
    $transaction = commerce_payment_transaction_new('commerce_pipwave', $response['txn_id']);
    $transaction->instance_id = $payment_method['instance_id'];
    $transaction->currency_code = $response["currency_code"];
    $transaction->amount = commerce_currency_decimal_to_amount($response['amount'], $response["currency_code"]);
    $transaction->remote_id = $response["pw_id"];
    $transaction->status_code = $response["transaction_status"];
    $with_warning_msg = ($response['status'] == 3001) ? " (with warning)" : '';
    
    $signature_param = array(
        'timestamp' => $response['timestamp'],
        'api_key' => variable_get("commerce_pipwave_api_key"),
        'pw_id' => $response['pw_id'],
        'txn_id' => $response['txn_id'],
        'amount' => $response['amount'],
        'currency_code' => $response['currency_code'],
        'transaction_status' => $response['transaction_status'],
        'api_secret' => variable_get('commerce_pipwave_api_secret'),
    );
    $signature = commerce_pipwave_generate_signature($signature_param);
    if ($response['signature'] == $signature) {
        if ($response["status"] == 200 || $response["status"] == 3001) {
            if ($response["transaction_status"] == 10) { // complete
                $transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;
                $transaction->message = t("Payment Status: Complete{$with_warning_msg}");
                $transaction->remote_status = 'Paid';
                commerce_order_status_update($order, 'processing');
            } else if ($response["transaction_status"] == 1) { // fail
                $transaction->status = COMMERCE_PAYMENT_STATUS_FAILURE;
                $transaction->message = t("Payment Status: Failed{$with_warning_msg}");
                $transaction->remote_status = 'Failed';
                commerce_order_status_update($order, 'canceled');
            } else if ($response["transaction_status"] == 2) { // cancel
                $transaction->status = COMMERCE_PAYMENT_STATUS_FAILURE;
                $transaction->message = t("Payment Status: Canceled{$with_warning_msg}");
                $transaction->remote_status = 'Canceled';
                commerce_order_status_update($order, 'canceled');
            } else if ($response["transaction_status"] == 5) {
                commerce_checkout_complete($order);
                $transaction->status = COMMERCE_PAYMENT_STATUS_PENDING;
                $transaction->message = t("Payment Status: Pending{$with_warning_msg}");
                $transaction->remote_status = 'Payment In Progress';
            } else if ($response["transaction_status"] == 20) { // refund
                $transaction->status = COMMERCE_PAYMENT_STATUS_SUCCESS;
                $transaction->message = t("Payment Status: Refunded{$with_warning_msg}");
                $transaction->remote_status = 'Refunded';
            } else {
                $transaction->status = COMMERCE_PAYMENT_STATUS_PENDING;
                $transaction->message = t("Undefined transaction status {$response["transaction_status"]}");
            }
        }        
    } else {
        $transaction->status = COMMERCE_PAYMENT_STATUS_PENDING;
        $transaction->message = t("Signature mismatch");
    }

    commerce_order_save($order);
    commerce_payment_transaction_save($transaction);
}

function commerce_pipwave_callback() {
    if (is_object(json_decode($post_content))) {
        $response = json_decode($post_content, true);
    } else {
        return false;
    }
    if (is_array($response)) {
        commerce_pipwave_redirect_form_validate($response, $order, $payment_method);
    }
}

function commerce_pipwave_send_request($data, $commerce_pipwave_test_mode) {
    // test mode is on
    if ($commerce_pipwave_test_mode == '1') {
        $url = "https://staging-api.pipwave.com/payment";
    } else {
        $url = "https://api.pipwave.com/payment";
    }

    $agent = "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0)";
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($data));
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_VERBOSE, 1);
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
    curl_setopt($ch, CURLOPT_TIMEOUT, 120);
    curl_setopt($ch, CURLOPT_USERAGENT, $agent);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
    $response = curl_exec($ch);
    if ($response == false) {
        echo "<pre>";
        echo 'CURL ERROR: ' . curl_errno($ch) . '::' . curl_error($ch);
        die;
    }
    curl_close($ch);
    return json_decode($response, true);
}

function commerce_pipwave_generate_signature($array) {
    ksort($array);
    $signature = "";
    foreach ($array as $key => $value) {
        $signature .= $key . ':' . $value;
    }
    return sha1($signature);
}
